version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get -y update
      - apt-get install awscli -y
      - echo "Installing JQ..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      
  pre_build:
    commands:
      - echo "Installing Terraform"
      - wget --quiet https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_*.zip -d /bin
      - chmod 755 /bin/terraform
      - terraform version
  build:
    commands:
      - terraform init -var 'env=dev' -var 'bucket_name=s3-terraform-bucket-23092019'
     # - terraform plan -var 'env=dev' -out=tfplan -var 'bucket_name=s3-terraform-bucket-23092019' -yes
      - terraform apply -var 'env=dev' -var 'bucket_name=s3-terraform-bucket-23092019'
    #  - bash ./build.sh $StackDetailsJSON
